### PR TITLE
Fix panic if trying to change profile without avatar set

### PR DESCRIPTION
**Pull request by dmitry-yudakov**
We noticed it with Andrey in attempt to change profile for guest - which maybe is incorrect situation but still no reason for crashing.

### CODE REVIEW

**Review by jor-rit — APPROVED** [review]
yes, LGTM. Panics are always bad, as a quickfix this looks OK. (ugly long line of nil checks, but that was already the case before this change, so it doesn't get much worse :)

**Comment by dmitry-yudakov** [comment]
Yeah, it seems golang community has rejected optional-chaining/safe-navigation operator proposal that would come handy in this case :) https://github.com/golang/go/issues/42847

They do offer some alternative solution with existing tools that's maybe worth considering in future https://github.com/golang/go/issues/42847#issuecomment-736858461

**Comment by jor-rit** [comment]
yeah, simplicity argument, I get their point.
Personally, I'd just go with something like `avatarChanged := isDifferentAvatar(inBody, userProfile)`.
And if you need it often in different places, track 'dirty' state inside the profile struct with setters.

**Comment by dmitry-yudakov** [comment]
I don't believe we'll need it somewhere else soon, so I'll merge it like this. And in the future we'll see.

**Pull request merged**
